--CREATE DATABASE LabOLAP_DB

CREATE TABLE Supplier
(
	ID INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	[Name] NVARCHAR(256) NOT NULL,
	RegDate DATE NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Staff
(
	ID INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	FullName NVARCHAR(256) NOT NULL,
	Email NVARCHAR(256),
	RegDate DATE NOT NULL DEFAULT GETDATE()
);

CREATE TABLE ProductType
(
	ID hierarchyid NOT NULL,
	[Type] NVARCHAR(256) NOT NULL,
	CONSTRAINT PK_ProductType_Hierarchy PRIMARY KEY CLUSTERED (ID ASC)
);

CREATE TABLE Shelf
(
	ID INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	Number INT NOT NULL,
	Quantity INT NOT NULL
);

CREATE TABLE SaleAnalytics
(
	ID INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	[Date] DATE NOT NULL DEFAULT GETDATE(),
	Quantity INT NOT NULL
);

CREATE TABLE Product
(
	ID INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	ProductTypeID hierarchyid NOT NULL,
	ProductName NVARCHAR(256) NOT NULL,
	SupplierID INT NOT NULL,
	CONSTRAINT FK_ProductSupplierID_To_Supplier FOREIGN KEY (SupplierID) REFERENCES Supplier(ID),
	CONSTRAINT FK_ProductProductTypeID_To_ProductType FOREIGN KEY (ProductTypeID) REFERENCES ProductType(ID),
);

CREATE TABLE Sales
(
	ID INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	StaffID INT NOT NULL,
	ProductID INT NOT NULL,
	SalesAnalyticsID INT NOT NULL,
	CONSTRAINT FK_SalesSSalesAnalyticsID_To_SalesAnalytics FOREIGN KEY (SalesAnalyticsID) REFERENCES SaleAnalytics(ID),
	CONSTRAINT FK_SalesProductID_To_Product FOREIGN KEY (ProductID) REFERENCES Product(ID),
	CONSTRAINT FK_SalesStaffID_To_Staff FOREIGN KEY (StaffID) REFERENCES Staff(ID)
);

CREATE TABLE Store
(
	ID INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	ShelfID INT NOT NULL,
	ProductID INT NOT NULL,
	StaffID INT NOT NULL,
	OperType CHAR(3) NOT NULL,
	StoreDate DATE NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_StoreStaffID_To_Staff FOREIGN KEY (StaffID) REFERENCES Staff(ID),
	CONSTRAINT FK_StoreProductID_To_Product FOREIGN KEY (ProductID) REFERENCES Product(ID),
	CONSTRAINT FK_StoreShelfID_To_Shelf FOREIGN KEY (ShelfID) REFERENCES Shelf(ID)
);

CREATE TABLE Invoice
(
	ID INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	StaffID INT NOT NULL,
	InvoiceName NVARCHAR(256) NOT NULL,
	StoreID INT NOT NULL,
	Price FLOAT NOT NULL,
	InvoiceDate DATE NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_InvoiceStoreID_To_Store FOREIGN KEY (StoreID) REFERENCES Store(ID),
	CONSTRAINT FK_InvoiceStaffID_To_Staff FOREIGN KEY (StaffID) REFERENCES Staff(ID)
);