USE LabOLAP
GO

SELECT PRODUCT FROM STORE
GROUP BY PRODUCT
HAVING COUNT(DISTINCT SUPPLIER) = 1

GO

SELECT SUM(TRY_CONVERT(int, QUANTITY)) AS SUMM FROM STORE
GROUP BY SHELF
HAVING SUM(TRY_CONVERT(int, QUANTITY)) <= 30

GO

SELECT INVOICE_DATE FROM INVOICE 
WHERE FORMAT(TRY_CONVERT(date, INVOICE_DATE) , 'dd/mm/yyyy') 
BETWEEN '01.01.2011' AND '31.05.2014'

GO

SELECT ID_STUFF, STAFF_NAME FROM INVOICE
GROUP BY ID_STUFF, STAFF_NAME
HAVING COUNT(DISTINCT STAFF_NAME) = 1
AND COUNT(DISTINCT E_MAIL) = 1

GO

SELECT * FROM STORE 
WHERE UPPER(OPER_TYPE) 
LIKE 'OUT' OR UPPER(OPER_TYPE) LIKE 'IN'

GO
USE LabOLAP_DB
GO

SELECT * FROM ProductType ptt
FULL OUTER JOIN 

(SELECT p.ProductTypeID AS 'ID', p.ProductTypeID.ToString() AS 'Root', p.ProductTypeID.GetLevel() AS 'Lvl',
	pt.Type, COUNT(*) AS 'SUM' FROM ProductType pt
INNER JOIN Product p ON p.ProductTypeID = pt.ID
GROUP BY p.ProductTypeID, pt.Type) AS Counted ON Counted.ID = ptt.ID